#!/bin/bash

cd $(dirname $0)

INSTALL=0
if [ ! -d .env ]; then
    INSTALL=1
    python3 -m venv .env
fi

. ./.env/bin/activate

if [ "${INSTALL}" = "1" ]; then
    pip install -r requirements.txt
fi

python3 ./doorbell.py

deactivate
